React & Redux group project - Space Travelers' Hub
chimwemwe007/space-travellers-hub pull request #30
Opened 2022-09-02 16:42 UTC by chimwemwe007

### In this project we did the following:

### Create pages
- Create rocket page and fetch rocket date from API to dispatch an action to store the selected data in Redux store:
- Created mission page and fetch mission data from API to dispatch an action to store the selected data in Redux store:
- Created profile page and fetch profile data from API and display selected joined and leaved mission. reserve rocket 

### Use Redux to do the following:
- Use useSelector() Redux Hook to select the state slices and render lists of rockets and missions in corresponding routes.
- Render a table with the missions' data (as per design).
- Write actions and reducers for booking rockets and joining missions.
- Place all logic in the reducer. In the React view file, only dispatch the action with the correct rocket ID as an argument.
- Write actions and reducers for canceling rockets and leaving missions.

2022-09-02 20:05 UTC, BenMukebo requested changes
## Hi @Lordkaito, @hamayounali5, @Hamayounali,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


### To Highlight 🎉

- Git flow is followed. :heavy_check_mark:
- You have followed  JavaScript best practices. ✔️ 
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️
- `useSelector()` was used to get a state slice corresponding to routes. ✔️ 
- Renders a list of rockets (as per design). ✔️ 
- Renders a table with the missions' data (as per design). ✔️ 

## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers :clinking_glasses:  and Happy coding!!! :dancers:💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-02 20:05 UTC, BenMukebo commented on src/components/ProfileComponents.js
> +      <div className="row">
- [OPTIONAL] The My Profile section can be enhanced by adding the "Cancel reservation" and "Leave Mission" buttons to the lists here. Clicking them should dispatch the actions you have already used in the main Rockets and Missions sections. 👍🏻 

- [OPTIONAL] The My Profile section can be enhanced by adding the "Read more" button for each mission and rocket. Upon click, it should open a corresponding Wikipedia page in a new tab. NOTE - you need to get that extra Wikipedia URL from the API's payload. 👍🏻

2022-09-02 20:44 UTC, chimwemwe007 commented on README.md
> +- LinkedIn: [Chimwemwe Mkandawire](https://www.linkedin.com/in/Chimwemwe-Mkandawire)
Hello @BenMukebo ,
- There are 2 group member in the team, we both just have 2 accounts linked to us both and we dont know how to deactivate our accounts. It is just 2 people both with an extra account.

2022-09-02 20:50 UTC, chimwemwe007 commented on README.md
> +Feel free to check the issues page.
Fixed

2022-09-03 02:15 UTC, Hamayounali commented on src/components/Navbar.js
> +            <Link className="nav-link" to="/profile">My Profile</Link>
Thank you @BenMukebo, I have updated the link as you guided.

2022-09-03 02:17 UTC, Hamayounali commented on src/components/Navbar.js
> +          </li>
Dear @BenMukebo, our team has 2 members, @Hamayounali and @chimwemwe007. Mistakenly we used other GitHub accounts.

2022-09-03 03:42 UTC, elisha2kyakpo1 approved these changes
Hi 👋 team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You did well to make the changes requested by the previous reviewer✔️✔️

## Optional suggestions

- [ ] Let's take note to correct optional changes as well.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-03 10:53 UTC, BenMukebo commented on src/components/Navbar.js
> +          </li>
Hey @Hamayounali, Let's ignore the Dragons part then 👍🏻

2022-09-03 13:07 UTC, merged